### ISSUE TITLE
Console spam about copper flowers

### ISSUE THREAD

**Issue by Dominance** [Draco18s/HarderStuff#4] opened 2015-09-14 06:20 UTC
http://paste.ubuntu.com/12406570/ I am having the person switch https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/HarderOres.cfg#L52  to 1 instead of 2 to see if it helps.

**Comment by Towsty** [comment] 2015-09-14 06:37
After changing the config of copper from 2 to 1 the console spam was much, much less. However, it quickly began to generate the same console spam for lead, I have since gone and set all flowers from 2 to 1 to see if it helps.

**Comment by Towsty** [comment] 2015-09-14 06:58
It seems that the mod may be overwritting the config, At this point, I changed all the OreExists numbers from 2 to 1, after rebooting the server however Silver, Lead, and Uranium have returned to a value of 2. I redid the whole process withe the same result. Copper is set to 1 and continues to produce a great deal of spam along with the other flowers. Here is the latest log:

https://www.dropbox.com/s/kx3e8h22563zfmv/1%20fml-server-latest.log?dl=0

**Comment by Draco18s** [comment] 2015-09-14 14:30
Ok, so it seems my latest fixes _don't work_ as well as intended.

The values in the config are intended to work as follows:
2) My ore was detected in the world previously, we need to register recipes, even if the oredict says there were no entries (this is due to the forced-placement option in COG).
1) Default, if my ore is detected during chunkgen, this _will_ be changed to 2
0) Skip!  This will also disable flower placement for non-RR ores.

That said, the "console spam" is due to _one of my own blocks_ somehow missing the flower data.  Which isn't governed by that setting.  Here's the bit that's interesting though:

[01:10:07] [Server thread/INFO] [STDOUT/]: Hard Ore block, tile.ore_iron has no flower data.  This is a bug!
[01:10:07] [Server thread/INFO] [STDOUT/]:     tile.ore_iron:-1 true

Da fuq?  It friggin matches in the debug info, but not in the lookup?  This also has nothing to do with copper or lead, but iron.

**Comment by Towsty** [comment] 2015-09-14 17:01
Any other information I can provide to help?

**Comment by Draco18s** [comment] 2015-09-14 17:15
Unfortunately and unhelpfully, no.  There's something weird going on and I'm not sure how to diagnose it.

**Comment by Towsty** [comment] 2015-09-14 17:47
I know this does not help narrow it down at all but it happens with more than just iron:

[12:34:36] [Server thread/INFO] [/]: Hard Ore block, tile.ore_gold has no flower data.  This is a bug!
[12:34:36] [Server thread/INFO] [/]: Listing all mapped blocks:
[12:34:36] [Server thread/INFO] [/]:     tile.ore_iron:-1 false
[12:34:36] [Server thread/INFO] [/]:     tile.ore_gold:-1 true

**Comment by Draco18s** [comment] 2015-09-14 17:55
That just confuses me even more.  Its like my wrapper that makes up the HashTable key isn't correctly implementing HashCode (or equals?) but I _don't_ get the problem in dev....

**Comment by Towsty** [comment] 2015-09-14 18:10
I loaded up a SSP world with the same build that the server is having issues with. No porblems with worldgen, no extra console logging, nothin. Works perfectly in SSP, I'm going to do some more testing in SMP

**Comment by Draco18s** [comment] 2015-09-14 18:26
The flower data reg. is common code.  I don't know why the server would have a fit.

**Comment by Dominance** [comment] 2015-09-14 19:53
Towsty are you sure the server is not running Kcauldron? Not sure if that matters but my own server using forge with 5 active players I have yet to encounter the spam. Then again a server I know that is using Kcauldron has not reported this issue to me ether.

**Comment by Towsty** [comment] 2015-09-14 19:59
This was from a Forge server, I have switched to KCauldron to do some testing with the same results. I've tried generating a new world (KCauldron) but it had the same errors. 

Edit - Summary:

Forge Server - Errors Began (Beyond Reality Divergence 1.1.8)
Errors persisted through updates
Currently tested KCauldron and Forge on Divergence 2.1.1
AMD System
Java 1.8
Ubuntu Server 15

**Comment by Towsty** [comment] 2015-09-14 23:09
I have done enough testing now to confirm that this is specific to my world. I created a fresh forge-based server on a different system to test and it worked fine. I copied that server to the system that my current Divergence build was on and it worked fine as well. I copied my current world folder into the same directory as my new test server and the same error occurred.

Before I start my world from scratch, do you know if there is anything that is generated in the world folder that could have been corrupted? If so, where is it and could I delete it to see if it regenerates correctly?

**Comment by Draco18s** [comment] 2015-09-14 23:12
I do store some data in the chunks themselves, but that should not cause the described behavior.

But if a new world fixes it, then all I can do is shrug and say that you should just do that.

**Comment by Towsty** [comment] 2015-09-14 23:14
Will do. Thanks for the help, looks like I've got some creative moving to do

**Comment by Draco18s** [comment] 2015-09-14 23:18
Yeah.  Unfortunate, but the 'bug' has me completely stumped and only affects the one world that I know of.

**Closed as completed by Draco18s** 2015-09-14 23:18 UTC

**Comment by Dominance** [comment] 2015-09-15 03:05
Seems as if he is not alone. Looked today when I got home http://paste.ubuntu.com/12415027/ Pure forge with forced ores on via XML.

**Comment by Draco18s** [comment] 2015-09-15 03:15
I don't get it.  I really don't.  The object its looking for is clearly there...

**Comment by Dominance** [comment] 2015-09-15 04:56
I wish I knew I see the same thing makes no since to me at all.

**Comment by Dominance** [comment] 2015-09-20 00:04
Hey still having this spam reported by servers. One of the servers it causes it to hang up. also inside chunks that is reporting the spam players get disconnected as well. Not sure if your still looking into this or not or if it is even something that is fixable.

**Comment by Draco18s** [comment] 2015-09-20 00:04
I can turn off the logging, but I don't know what's causing the underlying issue.

**Comment by Dominance** [comment] 2015-09-20 00:29
You know my own server had this spam for a bit and then it just stopped. It is very hard to track.

**Comment by Dominance** [comment] 2015-09-20 07:51
Here is a Log from a player in SSP https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/83
