### ISSUE TITLE
Harder Wildlife crash on upgrade.

### ISSUE THREAD

**Issue by nmarshall23** [Draco18s/HarderStuff#16] opened 2016-05-11 21:23 UTC
After I upgraded Harder Wildlife, I get a Ticking entity crash when I create or log into a world. 

Here is the crash [log](http://pastebin.com/0cXY6AEv).

**Comment by Draco18s** [comment] 2016-05-11 23:11
I know what the problem is, whoops.
There'll be a fix for this coming out tonight/tomorrow that'll fix this.

**Comment by Haggle1996** [comment] 2016-05-14 15:34
With the updated Harder Wildlife, now getting this crash: 

http://pastebin.com/tY3jy9mb

**Comment by Draco18s** [comment] 2016-05-14 16:28
Grumble grumble.  What weird thing causes something to break this time.
Jesus christ, why?  What the hell?
I don't even know how to make that crash occur.  I cannot guess how the entity's world is null.  But apparently it can be.  Joy.

**Comment by Draco18s** [comment] 2016-05-14 16:40
New version uploaded to curse, should be visible in 20 minutes or so.

**Closed as completed by Draco18s** 2016-05-14 16:40 UTC

**Comment by Haggle1996** [comment] 2016-05-14 16:47
If I only knew how to send you copious amounts of the alcohol of your choice, I would. Thanks!

**Comment by Draco18s** [comment] 2016-05-14 17:14
Haha!
